name: CI

on:
  pull_request:
    types: [closed]
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - .vscode
      - .husky

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
          run_install: true

      - name: Set node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: pnpm
      - run: pnpm run typecheck

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: pnpm

      - run: pnpm run build
      - run: pnpm run build:docs
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-dist
